name: build

on:
  push:
    branches-ignore: main

jobs:
  setup:
    uses: ./.github/workflows/_setup.yml

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
      - uses: actions/cache@v4
        id: build-cache
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-next-build-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}-next-build-
      - name: Run build
        if: steps.build-cache.outputs.cache-hit != 'true'
        run: pnpm install && corepack enable pnpm && pnpm build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
